# Generated by Django 4.1.2 on 2022-12-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_trade', models.CharField(max_length=10)),
                ('win_percentage', models.IntegerField()),
                ('currency_pair', models.CharField(max_length=20)),
                ('analysis', models.CharField(max_length=1000)),
                ('broker', models.CharField(max_length=20)),
                ('entry_time', models.TimeField()),
            ],
        ),
    ]
