# Generated by Django 4.1.2 on 2022-12-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='trade',
            name='win_percentage',
        ),
        migrations.AddField(
            model_name='trade',
            name='result',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Loss')], default='W', max_length=5),
        ),
        migrations.AlterField(
            model_name='trade',
            name='analysis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='currency_pair',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type_of_trade',
            field=models.CharField(choices=[('U', 'Up'), ('D', 'Down')], default='U', max_length=5),
        ),
    ]
